apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: lkoirala
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/laxmankoiralaharborproject/db@sha256:64bcab31e62a147f788c84ffba076321973cc1a4b66bd8ac210b71cad08ee4ce
        ports:
        - containerPort: 5432
